#! /bin/sh

~/.local/bin/polybar_start

if [[  ${HOSTNAME} == 'arch-desktop' ]]; then
    bspc monitor DP-0 -d 1 2 3 4 5
    bspc monitor HDMI-0 -d 6 7 8 9 10
    echo 'run' >> bspwm.log
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    echo 'dont run' >> bspwm.log
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^1'
bspc rule -a urxvt desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

bspc rule -a \*:"URxvtFuzzy" state=floating center=on sticky=on
bspc rule -a \*:"NeoMutt" state=floating center=on sticky=on
bspc rule -a \*:"filemanager" state=floating center=on sticky=on
