#! /bin/sh

sxhkd &
nitrogen --restore &
picom &
# xcompmgr -c -C -t-5 -l-5 -r4.2 -o.55 -Ff &

if [[  ${HOSTNAME} == 'arch-desktop' ]]; then
    ~/.screenlayout/lenovoacer.sh &
    bspc monitor DP-0 -d 1 2 3 4 5
    bspc monitor DVI-I-1 -d 6 7 8 9 10
else
    # ~/.local/bin/dockToggle
    # ~/.screenlayout/docked.sh
    if [[ $(bspc query --monitors | wc -l) > 1 ]]; then
        bspc monitor HDMI-3 -d 1 2 3 4 5
        bspc monitor HDMI-2 -d 6 7 8 9 10
    elif [[ $(bspc query --monitors | wc -l) == 1 ]]; then
        bspc monitor -d 1 2 3 4 5 6 7 8 9 10
    else
        bspc monitor -d ''
    fi
fi

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       fale
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

~/.local/bin/polybar_start
volumeicon &
nm-applet &

bspc rule -a Chromium desktop='^1'
bspc rule -a urxvt desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Alacritty:neovim desktop=10 follow=on

bspc rule -a \*:"URxvtFuzzy" state=floating center=on sticky=on
bspc rule -a \*:"NeoMutt" state=floating center=on sticky=on
bspc rule -a \*:"filemanager" state=floating center=on sticky=on
bspc rule -a \*:"dman" state=floating center=on
bspc rule -a Pcmanfm state=floating
bspc rule -a Spotify:spotify state=floating
